### ISSUE TITLE
Collection paragraph metadata

### ISSUE THREAD

**Issue by daltonj** [dfcf93/MSMARCOV2#19]
The collection.tsv contains the paragraph contents.  How do we get the metadata?  It's in the full documents, but I don't see how these can easily be linked.

**Comment by daltonj** [comment]
Let me be more specific.  The collections.tsv doesn't have basics - the URL, the Title; only text. These metadata fields are included in fulldocuments.  But - how are these linked back to paragraphs?  

Maybe I'm missing something obvious. A readme on the data and how to to use them / join them would be helpful.  I believe some students have an earlier version where the paragraphs were grouped by query with titles / urls. But I don't see this for the ranking dataset.  A description of what's in each would be helpful.

**Comment by dfcf93** [comment]
Answered earlier on slack but the simple answer is there is no metadata in the collections file but you can do a lookup in the regular Q&A file and do a join on passages. Ill add this to my backlog to create.
