### ISSUE TITLE
some bugs about the code 

### ISSUE THREAD

**Issue by javacjh** [dfcf93/MSMARCOV2#2]
some adaptation is needed for code downloaded. Otherwise, it will generate errors. (Actually we can change the output file also but I simply change the code downloaded)
1. for Evaluation/bleu/bleu.py line22 assert(list(gts.keys()) == list(res.keys())) should be changed to 
assert(sorted(gts.keys()) == sorted(res.keys()))
2. for Evaluation/rouge/rouge.py line85 assert(list(gts.keys()) == list(res.keys())) should be changed to 
assert(sorted(gts.keys()) == sorted(res.keys()))
3. for Evaluation/ms_marco_eval.py line 132 133
precision = true_positives/(true_positives+false_positives)
recall = true_positives/(true_positives+false_negatives)
should be changed to 
precision = float(true_positives)/(true_positives+false_positives) if (true_positives+false_positives)>0 else 1.
recall = float(true_positives)/(true_positives+false_negatives) if (true_positives+false_negatives)>0 else 1.
in case divide zero

**Comment by ChinHui-Chen** [comment]
Hi @javacjh,

Do u encounter this error?

![image](https://user-images.githubusercontent.com/625355/40792579-df6d32fa-652c-11e8-9c55-d90cd70de680.png)

**Comment by dfcf93** [comment]
Thanks for the keen eye. Ive updated eval scripts with this input.

**Comment by dfcf93** [comment]
@ChinHui-Chen please open another issue focused on baseline errors describing your setup, what commands you are running and I'll take a look

**Comment by javacjh** [comment]
Hi there:

I only run the code in evaluation so I don't know what happen to other
code. So far I have coded with tensorflow, so I am not so familiar with
torch.
Based on the information you provided, the error occur at line 154 of
train.py. You may check whether it's typo about queries or the problem
about the format of queries variable.

Best,
Jiahua
