### ISSUE TITLE
there are many bugs in the evaluation script

### ISSUE THREAD

**Issue by xinyadu** [dfcf93/MSMARCOV2#3]
it even cannot run through sample test cases the author provided

**Comment by wise-east** [comment]
I ran into the same problem while running the sample cases. 
```
Traceback (most recent call last):
  File "ms_marco_eval.py", line 20, in <module>
    from rouge.rouge import Rouge
  File "/Users/justincho/Desktop/Imago/Computer comprehension/MSMARCOV2/Evaluation/rouge/rouge.py", line 86
    imgIds = list(gts.keys())
```
If you happened to get this error, just go to the rouge.py file and add another ")" to the end of line 86

I then got the following error:
```
OSError: [E050] Can't find model 'en_core_web_lg'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```

This means you don't have this particular model from spacy downloaded, even if you have installed spacy. Run the following in your terminal: 
`pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-2.0.0/en_core_web_lg-2.0.0.tar.gz`

I actually still have a problem with one set of the sample files when I run `. run.sh sample_test_data/no_answer_test_references.json sample_test_data/no_answer_test_candidates.json `, but the script will work fine for this set: 
`. run.sh sample_test_data/sample_references.json sample_test_data/sample_candidates.json`

I hope this helped.
